EXPERIMENT:
  NAME: "lung_baselines_vanilla_vit_test"
  TAG: "vanilla,convnext_v2"
  PROJECT: "/home/data/lh/test_result"
DISTILLER:
  TYPE: "NONE"
  TEACHER: "resnet32x4"
  STUDENT: "vit"
SOLVER:
  BATCH_SIZE: 32
  EPOCHS: 100
  LR: 5e-5
  LR_DECAY_STAGES: [25,50,75]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 1e-8
  MOMENTUM: 0.9
  TYPE: "AdamW"
